prjVisaSupplier/Controllers/TVordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjVisaSupplier.Models;

namespace prjVisaSupplier.Controllers
{
    public class TVordersController : Controller
    {
        private readonly dbTravalPlatformContext _context;

        public TVordersController(dbTravalPlatformContext context)
        {
            _context = context;
        }

        // GET: TVorders
        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> IndexOld()
        {
            var dbTravalPlatformContext = _context.TVorders;
            return View(await dbTravalPlatformContext.ToListAsync());
        }

        [Route("/TVorders/IndexJson")]
        public JsonResult IndexJson()
        {
            var VOrders = _context.TVorders
                                            .Include(t => t.FCoupon)
                                            .Include(t => t.FCustomer)
                                            .Include(t => t.FProduct)
                                            .Include(t => t.FStatus)
                                            .Select(t => new
                                            {
                                                fOrderId = t.FOrderId,
                                                fProductName = t.FProduct.FName,
                                                fCustomerName = t.FCustomer.FName,
                                                fPrice = t.FProduct.FPrice,
                                                fQuantity = t.FQuantity,
                                                fDepartureDate = t.FDepartureDate,
                                                fInterviewRequirement = t.FProduct.FInterviewRequirement,
                                                fEntityOrElectric = t.FProduct.FEntityOrElectronic,
                                                fForPickupOrDeliveryAddress = t.FForPickupOrDeliveryAddress,
                                                fInterviewReminder = t.FInterviewReminder,
                                                fEvaluate = t.FEvaluate,
                                                fCoupon = t.FCoupon.FCouponName,
                                                fTotal = t.FProduct.FPrice * t.FQuantity - t.FCoupon.FDiscount,
                                                fMemo = t.FMemo,
                                                fStatus = t.FStatus.FVorderStatus

                                            });
            //var VOrders = from o in _context.TVorders
            //              join co in _context.TCouponLists on o.FCouponId equals co.FCouponId
            //              join cu in _context.TCustomers on o.FCustomerId equals cu.FCustomerId
            //              join p in _context.TVproducts on o.FProductId equals p.FId
            //              join st in _context.TVorderStatuses on o.FStatusId equals st.FId
            //              select new
            //              {
            //                  fOrderId = o.FOrderId,
            //                  fProductName = p.FName,
            //                  fCustomerName = cu.FName,
            //                  fPrice = p.FPrice,
            //                  fQuantity = o.FQuantity,
            //                  fDepartureDate = o.FDepartureDate,
            //                  fInterviewRequirement = p.FInterviewRequirement,
            //                  fEntityOrElectric = p.FEntityOrElectronic,
            //                  fForPickupOrDeliveryAddress = o.FForPickupOrDeliveryAddress,
            //                  fInterviewReminder = o.FInterviewReminder,
            //                  fEvaluate = o.FEvaluate,
            //                  fCoupon = co.FCouponName,
            //                  fTotal = p.FPrice * o.FQuantity - co.FDiscount,
            //                  fMemo = o.FMemo,
            //                  fStatus = st.FVorderStatus
            //              };
            return Json(VOrders);
        }


        // GET: TVorders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TVorders == null)
            {
                return NotFound();
            }

            var tVorder = await _context.TVorders
                .Include(t => t.FCoupon)
                .Include(t => t.FCustomer)
                .Include(t => t.FProduct)
                .Include(t => t.FStatus)
                .FirstOrDefaultAsync(m => m.FId == id);
            if (tVorder == null)
            {
                return NotFound();
            }

            return View(tVorder);
        }

        // GET: TVorders/Create
        public IActionResult Create()
        {
            ViewData["FCouponId"] = new SelectList(_context.TCouponLists, "FCouponId", "FCouponName");
            ViewData["FCustomerId"] = new SelectList(_context.TCustomers, "FCustomerId", "FName");
            ViewData["FProductId"] = new SelectList(_context.TVproducts, "FId", "FName");
            ViewData["FStatusId"] = new SelectList(_context.TVorderStatuses, "FId", "FVorderStatus");
            return View();
        }

        // POST: TVorders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FId,FOrderId,FProductId,FCustomerId,FPrice,FQuantity,FDepartureDate,FForPickupOrDeliveryAddress,FInterviewReminder,FEvaluate,FMemo,FStatusId,FCouponId")] TVorder tVorder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tVorder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FCouponId"] = new SelectList(_context.TCouponLists, "FCouponId", "FCouponId", tVorder.FCouponId);
            ViewData["FCustomerId"] = new SelectList(_context.TCustomers, "FCustomerId", "FCustomerId", tVorder.FCustomerId);
            ViewData["FProductId"] = new SelectList(_context.TVproducts, "FId", "FName", tVorder.FProductId);
            ViewData["FStatusId"] = new SelectList(_context.TVorderStatuses, "FId", "FId", tVorder.FStatusId);
            return View(tVorder);
        }

        // GET: TVorders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TVorders == null)
            {
                return NotFound();
            }

            var tVorder = await _context.TVorders.FindAsync(id);
            if (tVorder == null)
            {
                return NotFound();
            }
            ViewData["FCouponId"] = new SelectList(_context.TCouponLists, "FCouponId", "FCouponId", tVorder.FCouponId);
            ViewData["FCustomerId"] = new SelectList(_context.TCustomers, "FCustomerId", "FCustomerId", tVorder.FCustomerId);
            ViewData["FProductId"] = new SelectList(_context.TVproducts, "FId", "FName", tVorder.FProductId);
            ViewData["FStatusId"] = new SelectList(_context.TVorderStatuses, "FId", "FId", tVorder.FStatusId);
            return View(tVorder);
        }

        // POST: TVorders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FId,FOrderId,FProductId,FCustomerId,FPrice,FQuantity,FDepartureDate,FForPickupOrDeliveryAddress,FInterviewReminder,FEvaluate,FMemo,FStatusId,FCouponId")] TVorder tVorder)
        {
            if (id != tVorder.FId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tVorder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TVorderExists(tVorder.FId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FCouponId"] = new SelectList(_context.TCouponLists, "FCouponId", "FCouponId", tVorder.FCouponId);
            ViewData["FCustomerId"] = new SelectList(_context.TCustomers, "FCustomerId", "FCustomerId", tVorder.FCustomerId);
            ViewData["FProductId"] = new SelectList(_context.TVproducts, "FId", "FName", tVorder.FProductId);
            ViewData["FStatusId"] = new SelectList(_context.TVorderStatuses, "FId", "FId", tVorder.FStatusId);
            return View(tVorder);
        }

        // GET: TVorders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TVorders == null)
            {
                return NotFound();
            }

            var tVorder = await _context.TVorders
                .Include(t => t.FCoupon)
                .Include(t => t.FCustomer)
                .Include(t => t.FProduct)
                .Include(t => t.FStatus)
                .FirstOrDefaultAsync(m => m.FId == id);
            if (tVorder == null)
            {
                return NotFound();
            }

            return View(tVorder);
        }

        // POST: TVorders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

prjVisaSupplier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prjVisaSupplier</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/prjVisaSupplier.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">prjVisaSupplier</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVorders" asp-action="Index">訂單</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVorders" asp-action="IndexJson">訂單Json</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVproducts" asp-action="Index">商品</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVproducts" asp-action="IndexJson">商品Json</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVproducts" asp-action="Earth">earth</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TVproducts" asp-action="amchart3">amchart3</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - prjVisaSupplier - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>